/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author misha
 */
import java.io.*;
public class MarathonIOForm2 extends javax.swing.JFrame {

    /**
     * Creates new form MarathonIOForm2
     */
    public MarathonIOForm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timelbl1 = new javax.swing.JLabel();
        runnerlbl8 = new javax.swing.JLabel();
        timelbl2 = new javax.swing.JLabel();
        timelbl3 = new javax.swing.JLabel();
        timelbl4 = new javax.swing.JLabel();
        timelbl5 = new javax.swing.JLabel();
        timelbl6 = new javax.swing.JLabel();
        timelbl7 = new javax.swing.JLabel();
        marathonlbl6 = new javax.swing.JLabel();
        timelbl8 = new javax.swing.JLabel();
        marathonlbl7 = new javax.swing.JLabel();
        buttonbtn = new javax.swing.JButton();
        marathonlbl8 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        runnerlbl6 = new javax.swing.JLabel();
        ranklbl = new javax.swing.JLabel();
        runnerlbl3 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        runnerlbl4 = new javax.swing.JLabel();
        runnerlbl5 = new javax.swing.JLabel();
        runnerlbl1 = new javax.swing.JLabel();
        titlelbl = new javax.swing.JLabel();
        introlbl = new javax.swing.JLabel();
        marathonlbl1 = new javax.swing.JLabel();
        marathonlbl3 = new javax.swing.JLabel();
        marathonlbl2 = new javax.swing.JLabel();
        marathonlbl4 = new javax.swing.JLabel();
        marathonlbl5 = new javax.swing.JLabel();
        runnerlbl2 = new javax.swing.JLabel();
        runnerlbl7 = new javax.swing.JLabel();
        pacelbl = new javax.swing.JLabel();
        pacelbl1 = new javax.swing.JLabel();
        pacelbl2 = new javax.swing.JLabel();
        pacelbl3 = new javax.swing.JLabel();
        pacelbl4 = new javax.swing.JLabel();
        pacelbl5 = new javax.swing.JLabel();
        pacelbl6 = new javax.swing.JLabel();
        pacelbl7 = new javax.swing.JLabel();
        pacelbl8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timelbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl1.setText("- : - - : - -");

        runnerlbl8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl8.setText("- - - - - - - - - - - - - - - - - - - -");

        timelbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl2.setText("- : - - : - -");

        timelbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl3.setText("- : - - : - -");

        timelbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl4.setText("- : - - : - -");

        timelbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl5.setText("- : - - : - -");

        timelbl6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl6.setText("- : - - : - -");

        timelbl7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl7.setText("- : - - : - -");

        marathonlbl6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl6.setText("#6");

        timelbl8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl8.setText("- : - - : - -");

        marathonlbl7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl7.setText("#7");

        buttonbtn.setText("Get Data");
        buttonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbtnActionPerformed(evt);
            }
        });

        marathonlbl8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl8.setText("#8");

        namelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelbl.setText("Runner Name");

        runnerlbl6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl6.setText("- - - - - - - - - - - - - - - - - - - -");

        ranklbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ranklbl.setText("All Time Rank");

        runnerlbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl3.setText("- - - - - - - - - - - - - - - - - - - -");

        timelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timelbl.setText("Time ");

        runnerlbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl4.setText("- - - - - - - - - - - - - - - - - - - -");

        runnerlbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl5.setText("- - - - - - - - - - - - - - - - - - - -");

        runnerlbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl1.setText("- - - - - - - - - - - - - - - - - - - -");

        titlelbl.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titlelbl.setText("Marathon Info");

        introlbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        introlbl.setText("Click the button below to learn more about some of the fastest marathon runners of all time");

        marathonlbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl1.setText("#1");

        marathonlbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl3.setText("#3");

        marathonlbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl2.setText("#2");

        marathonlbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl4.setText("#4");

        marathonlbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        marathonlbl5.setText("#5");

        runnerlbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl2.setText("- - - - - - - - - - - - - - - - - - - -");

        runnerlbl7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        runnerlbl7.setText("- - - - - - - - - - - - - - - - - - - -");

        pacelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl.setText("Pace");

        pacelbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl1.setText("- : - - / km");

        pacelbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl2.setText("- : - - / km");

        pacelbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl3.setText("- : - - / km");

        pacelbl4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl4.setText("- : - - / km");

        pacelbl5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl5.setText("- : - - / km");

        pacelbl6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl6.setText("- : - - / km");

        pacelbl7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl7.setText("- : - - / km");

        pacelbl8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pacelbl8.setText("- : - - / km");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlelbl)
                            .addGap(307, 307, 307))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(316, 316, 316)
                            .addComponent(buttonbtn))
                        .addComponent(introlbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marathonlbl2)
                                    .addComponent(marathonlbl3)
                                    .addComponent(marathonlbl1)
                                    .addComponent(marathonlbl4)
                                    .addComponent(marathonlbl5)
                                    .addComponent(marathonlbl6)
                                    .addComponent(marathonlbl7)
                                    .addComponent(marathonlbl8)))
                            .addComponent(ranklbl))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(runnerlbl3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(runnerlbl2)
                                    .addComponent(runnerlbl7)
                                    .addComponent(runnerlbl6)
                                    .addComponent(runnerlbl5)
                                    .addComponent(runnerlbl4)
                                    .addComponent(runnerlbl1)
                                    .addComponent(runnerlbl8)))
                            .addComponent(namelbl))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timelbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(timelbl5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timelbl6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timelbl7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timelbl8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timelbl4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timelbl2)
                                .addComponent(timelbl1)
                                .addComponent(timelbl3)))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pacelbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pacelbl5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pacelbl6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pacelbl7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pacelbl8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pacelbl4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pacelbl2)
                                .addComponent(pacelbl1)
                                .addComponent(pacelbl3)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titlelbl)
                .addGap(18, 18, 18)
                .addComponent(introlbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonbtn)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelbl)
                            .addComponent(ranklbl)
                            .addComponent(timelbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl1)
                            .addComponent(runnerlbl1)
                            .addComponent(timelbl1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl2)
                            .addComponent(runnerlbl2)
                            .addComponent(timelbl2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl3)
                            .addComponent(runnerlbl3)
                            .addComponent(timelbl3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl4)
                            .addComponent(runnerlbl4)
                            .addComponent(timelbl4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl5)
                            .addComponent(runnerlbl5)
                            .addComponent(timelbl5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl6)
                            .addComponent(runnerlbl6)
                            .addComponent(timelbl6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl7)
                            .addComponent(runnerlbl7)
                            .addComponent(timelbl7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marathonlbl8)
                            .addComponent(runnerlbl8)
                            .addComponent(timelbl8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pacelbl)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl1)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl2)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl3)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl4)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl5)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl6)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl7)
                        .addGap(18, 18, 18)
                        .addComponent(pacelbl8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbtnActionPerformed
        //2 decimals
       
        //Strings for data
        String runnerName [] = new String [8];
        String runnerTime [] = new String [8];
        int timeInSeconds [] = new int [8];
        String pace [] = new String [8];
        try{
            FileReader file = new FileReader("Marathon.dat");
            BufferedReader buffer = new BufferedReader(file);
            for (int i = 0; i <=7; i++){
                runnerName[i] = buffer.readLine();
                runnerTime[i] = buffer.readLine();
            }
            buffer.close();
        }
        catch(IOException e){
            System.err.println("Sorry, file not found");   
        }
        for (int i = 0; i <=7; i++){
        System.out.println("Name " + runnerName[i] + ", Time: " + runnerTime[i]);
        }
        
        //Converting Time to seconds
        for (int i = 0; i <=7; i++){
             int time;
             //Hours
             char hours = runnerTime[i].charAt(0);
             String a = String.valueOf(hours);
             int secondsAt0 = 3600* (Integer.parseInt(a));
             
             //Tens of Minutes
             char minutes10 = runnerTime[i].charAt(2);
             String b = String.valueOf(minutes10);
             int secondsAt2 = 600* (Integer.parseInt(b));
             
             //Minutes
             char minutes1 = runnerTime[i].charAt(3);
             String c = String.valueOf(minutes1);
             int secondsAt3 = 60* (Integer.parseInt(c));
             
             //Tens of seconds
             char seconds10 = runnerTime[i].charAt(5);
             String d = String.valueOf(seconds10);
             int secondsAt5 = 10* (Integer.parseInt(d));
             
             //Seconds
             char seconds1 = runnerTime[i].charAt(6);
             String e = String.valueOf(seconds1);
             int secondsAt6 = (Integer.parseInt(e));
             
             //Adding up seconds
             time = secondsAt0 + secondsAt2 + secondsAt3 + secondsAt5 + secondsAt6;
             timeInSeconds[i] = time;
             System.out.println(timeInSeconds[i]);
         }
        //Time in seconds to pace
            for (int i = 0; i <=7; i++){
                double paceInSeconds = (timeInSeconds[i]/42.2);
                int pace2 = (int)paceInSeconds;
                int minutes = pace2 /60;
                int seconds = pace2 % 60;
                pace[i] = (String.valueOf(minutes) + ":" + String.valueOf(seconds) + "/km");
                System.out.println(pace[i]);
            }
            //Outputs
        runnerlbl1.setText(runnerName[0]);
        timelbl1.setText(runnerTime[0]);
        pacelbl1.setText(pace[0]);
        runnerlbl2.setText(runnerName[1]);
        timelbl2.setText(runnerTime[1]);
        pacelbl2.setText(pace[1]);
        runnerlbl3.setText(runnerName[2]);
        timelbl3.setText(runnerTime[2]);
        pacelbl3.setText(pace[2]);
        runnerlbl4.setText(runnerName[3]);
        timelbl4.setText(runnerTime[3]);
        pacelbl4.setText(pace[3]);
        runnerlbl5.setText(runnerName[4]);
        timelbl5.setText(runnerTime[4]);
        pacelbl5.setText(pace[4]);
        runnerlbl6.setText(runnerName[5]);
        timelbl6.setText(runnerTime[5]);
        pacelbl6.setText(pace[5]);
        runnerlbl7.setText(runnerName[6]);
        timelbl7.setText(runnerTime[6]);
        pacelbl7.setText(pace[6]);
        runnerlbl8.setText(runnerName[7]);
        timelbl8.setText(runnerTime[7]);
        pacelbl8.setText(pace[7]);

    }//GEN-LAST:event_buttonbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarathonIOForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarathonIOForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarathonIOForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarathonIOForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarathonIOForm2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonbtn;
    private javax.swing.JLabel introlbl;
    private javax.swing.JLabel marathonlbl1;
    private javax.swing.JLabel marathonlbl2;
    private javax.swing.JLabel marathonlbl3;
    private javax.swing.JLabel marathonlbl4;
    private javax.swing.JLabel marathonlbl5;
    private javax.swing.JLabel marathonlbl6;
    private javax.swing.JLabel marathonlbl7;
    private javax.swing.JLabel marathonlbl8;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel pacelbl;
    private javax.swing.JLabel pacelbl1;
    private javax.swing.JLabel pacelbl2;
    private javax.swing.JLabel pacelbl3;
    private javax.swing.JLabel pacelbl4;
    private javax.swing.JLabel pacelbl5;
    private javax.swing.JLabel pacelbl6;
    private javax.swing.JLabel pacelbl7;
    private javax.swing.JLabel pacelbl8;
    private javax.swing.JLabel ranklbl;
    private javax.swing.JLabel runnerlbl1;
    private javax.swing.JLabel runnerlbl2;
    private javax.swing.JLabel runnerlbl3;
    private javax.swing.JLabel runnerlbl4;
    private javax.swing.JLabel runnerlbl5;
    private javax.swing.JLabel runnerlbl6;
    private javax.swing.JLabel runnerlbl7;
    private javax.swing.JLabel runnerlbl8;
    private javax.swing.JLabel timelbl;
    private javax.swing.JLabel timelbl1;
    private javax.swing.JLabel timelbl2;
    private javax.swing.JLabel timelbl3;
    private javax.swing.JLabel timelbl4;
    private javax.swing.JLabel timelbl5;
    private javax.swing.JLabel timelbl6;
    private javax.swing.JLabel timelbl7;
    private javax.swing.JLabel timelbl8;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
